### ISSUE TITLE
Updater/Analyzer initialize()/execute(): How should they be used?

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#3]
The usage is still inconsistent. This can lead to problems e.g. when updaters set up the system in execute(), but analyzers require information about the final  system parameters already in their initialize().

**Comment by Bondoki** [comment]
Yes, this is really problematic. The most use cases do it the right way because we wrote it that way. We should first of all discuss which functionality in initialize() and execute() we're generally expect for updaters and analyzers. I think this is te tricky point. Maybe we should force that no updater and no analyzer should use information provided by over updaters/analyzers. But this will also lead to confusions, or?

**Comment by hrabbel** [comment]
To sum up the discussions here: After initialize(), updaters should have set up a consistent system. This implies that in initialize(), the analyzers can expect a consistent system, but not before. Thus, the constuctors of analyzers should not be using properies of the system which could still be set later. In fact, constructors should have empty bodies, as far as possible. 

In AnalyzerRadiusOfGyration, this needs to be fixed.

**Comment by hrabbel** [comment]
As far as I can tell this has been clarified. I suggest to close the issue.
