### ISSUE TITLE
FeatureExcludedVolume: Move for adding monomers not implemented

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#4]
The FeatureExcludedVolume::applyMove(IngredientsType&,MoveAddScMonomer&) must be implemented. Otherwise the lattice occupation will not be set up consistently when using the MoveAddScMonomer, which is potentially very dangerous. 

On the other hand: Should this feature be discontinued anyways? See related issue.

**Comment by Bondoki** [comment]
Honestly, I have to admit, I did not used MoveAddScMonomer at all. Most creation updaters are plain ScBFM by directly checking the vicinity, but I know this move MoveAddScMonomer is powerful and useful at all. I agree that the interface should be provided. And refering to the other open issue: maybe we write an general ExVolFeature or provide only two specialized variants ScBFM and BccBFM.

**Comment by MartinWenge** [comment]
I would suggest to provide two separated features for excluded volume as proposed by Ron. At the beginning you have to make the choice of your model either Sc or Bcc BFM, being physically different  realisations of a coarse-grained MC model. So we make a clear distinction between the models and avoid conflicts due to different implementations of the respective functions. Then we can implement an FeatureExcludedVolumeSc::apllyMove(IngredientsType&,MoveAddMonomer&) and  FeatureExcludedVolumeBcc::apllyMove(IngredientsType&,MoveAddMonomer&).

**Comment by hrabbel** [comment]
I totally agree.

**Comment by MartinWenge** [comment]
This bug was fixed by #33
